name: Upstream Sync & JA Translate

on:
  schedule:
    - cron: '0 15 * * *'  # 00:00 JST
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-and-translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork (origin)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools.git || true
          git fetch upstream main

      - name: Create working branch from upstream/main
        id: mkbranch
        run: |
          BRANCH="bot/ja-sync-$(date -u +%Y%m%d-%H%M%S)"
          git checkout -B "$BRANCH" upstream/main
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Import JA kit (.github) from fork (origin)
        run: |
          git fetch origin
          git checkout origin/main -- .github || git checkout origin/master -- .github
          ls -R .github

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install translation deps
        run: |
          pip install -r .github/translation/requirements.txt

      - name: Run translator (same filenames, structure-preserving)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # optional
          DEEPL_API_KEY:  ${{ secrets.DEEPL_API_KEY }}   # optional
        run: |
          python .github/translation/translate_repo.py

      - name: Validate JSON files
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          set -e
          for f in $(git ls-files '*.json'); do
            jq . "$f" >/dev/null || { echo "::error file=$f::invalid JSON"; exit 1; }
          done

      - name: Commit changes (if any)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "ja-sync-bot"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "chore(sync): upstream main → 日本語化（自動）"

      - name: Create Pull
